name: Puppeteer Automation

on:
  workflow_dispatch: # Run manually
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC (optional)

jobs:
  run-puppeteer:
    runs-on: ubuntu-latest # Ubuntu 24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Install Ubuntu 24.04 Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \


      - name: Run Puppeteer Script
        run: node puppeteer-script.js
