name: Run Puppeteer Script

on:
  workflow_dispatch:

jobs:
  puppeteer-job:
    runs-on: ubuntu-latest  # Ubuntu 24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm install puppeteer

      - name: Install System Libraries (Ubuntu 24.04 Fix)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2t64 \
            libatk-bridge2.0-0t64 \
            libatk1.0-0t64 \
            libcairo2t64 \
            libcups2t64 \
            libgbm1t64 \
            libgtk-4.1-0t64 \  # Updated for GTK 4
            libpango-1.0-0t64 \
            libxcomposite1t64 \
            libxdamage1t64 \
            libxfixes3t64 \
            libxrandr2t64 \
            libnss3t64 \       # Added missing dependency
            libdrm2t64 \       # Added missing dependency
            fonts-liberation \
            xdg-utils

      - name: Run Puppeteer Script
        run: node puppeteer-script.js
