name: Puppeteer Automation

on:
  workflow_dispatch: # Run manually
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC (optional)

jobs:
  run-puppeteer:
    runs-on: ubuntu-latest # Ubuntu 24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4



      - name: Run Puppeteer Script
        run: node puppeteer-script.js
