name: Yad2 Scraper
on: workflow_dispatch

jobs:
  scrape:
    runs-on: ubuntu-22.04
    env:
      PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium-browser"
      CAPTCHA_API_KEY: ${{ secrets.CAPTCHA_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Clean installation
        run: |
          rm -rf node_modules
          rm -f package-lock.json

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            chromium-browser \
            libnss3 \
            libxcomposite1 \
            libxrandr2 \
            libgbm1 \
            libgtk-3-0 \
            libasound2 \
            libatk-bridge2.0-0

      - name: Install npm packages
        run: |
          npm install
          npm fund

      - name: Run scraper
        run: npm start

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: results
          path: |
            cars.json
            error-logs/
          retention-days: 1
