name: Yad2 Car Scraper

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: |
          npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth
          # Install chromium explicitly
          sudo apt-get install -y chromium

      - name: Install system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcairo2 \
            libcups2 \
            libgbm1 \
            libgtk-3-0 \
            libnss3 \
            libpango-1.0-0 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libxrandr2 \
            libxkbcommon0 \  # Added missing dependency
            fonts-liberation \
            xdg-utils

      - name: Run scraper
        run: node scraper.js
        env:
          PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium"  # Point to system Chromium

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: car-listings
          path: |
            cars.json
            error.png
