# .github/workflows/scrape.yml
name: Yad2 Scraper
on: workflow_dispatch

jobs:
  scrape:
    runs-on: ubuntu-22.04
    env:
      CAPTCHA_API_KEY: ${{ secrets.CAPTCHA_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libxcomposite1 \
            libxrandr2 \
            libgbm1 \
            libgtk-3-0 \
            libasound2 \
            libatk-bridge2.0-0

      - name: Install npm packages
        run: npm ci --no-audit

      - name: Run scraper
        timeout-minutes: 10
        run: npm start

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: results
          path: |
            cars.json
            error.log
            error-logs/
            screenshots/
          retention-days: 1
