name: Yad2 Car Scraper

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install system dependencies
        run: |
          sudo add-apt-repository -y universe
          sudo apt-get update
          sudo apt-get install -y \
            chromium-browser \
            libasound2 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcairo2 \
            libcups2 \
            libgbm1 \
            libgtk-3-0 \
            libnss3 \
            libpango-1.0-0 \
            libxcomposite1 \
            libxdamage1 \
            libxfixes3 \
            libxrandr2 \
            libxkbcommon0 \
            fonts-liberation \
            xdg-utils

      - name: Install Node modules
        run: |
          npm install puppeteer@21.11.0 puppeteer-extra@3.3.6 puppeteer-extra-plugin-stealth@2.11.2

      - name: Run scraper
        run: node scraper.js
        env:
          PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium-browser"

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: car-listings
          path: |
            cars.json
            debug.log
            page.png
            error.png
