name: Yad2 Scraper
on: workflow_dispatch

jobs:
  scrape:
    runs-on: ubuntu-22.04
    env:
      PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium-browser"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            chromium-browser \
            libnss3 \
            libxcomposite1 \
            libxrandr2 \
            libgbm1
          npm ci
      - name: Run scraper
        run: node scraper.js
      - uses: actions/upload-artifact@v4
        with:
          name: results
          path: |
            cars.json
            *.png
            error.log
