name: Yad2 Scraper
on: workflow_dispatch

jobs:
  scrape:
    runs-on: ubuntu-22.04
    env:
      PUPPETEER_EXECUTABLE_PATH: "/usr/bin/chromium-browser"
      CAPTCHA_API_KEY: ${{ secrets.CAPTCHA_API_KEY }}
      NODE_DEBUG: "2captcha,puppeteer"
      DEBUG: "*"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            chromium-browser \
            libnss3 \
            libxcomposite1 \
            libxrandr2 \
            libgbm1 \
            libgtk-3-0 \
            libasound2 \
            libatk-bridge2.0-0

      - name: Install npm packages
        run: npm ci
        continue-on-error: true

      - name: Debug logs
        if: always()
        run: |
          echo "--- npm debug log ---"
          cat $(find /home/runner/.npm/_logs -name '*-debug.log' | sort | tail -1)
          
          echo "--- Environment ---"
          printenv
          
          echo "--- Installed Packages ---"
          npm list --depth=0

      - name: Run scraper
        run: npm start
        continue-on-error: true

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: results
          path: |
            cars.json
            error-logs/
            *.log
          retention-days: 7
