name: Yad2 Scraper
on: workflow_dispatch

jobs:
  scrape:
    runs-on: ubuntu-22.04
    env:
      CAPTCHA_API_KEY: ${{ secrets.CAPTCHA_API_KEY }}
      PUPPETEER_EXECUTABLE_PATH: '/usr/bin/google-chrome-stable'

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo rm -f /usr/bin/chromium
          sudo ln -s /usr/bin/google-chrome-stable /usr/bin/chromium

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --no-audit
      
      - run: npm start
      
      - uses: actions/upload-artifact@v4
        with:
          name: results
          path: |
            cars.json
            screenshots/
            error-logs/
